In [ ]:
!pip install sentence-transformers chromadb groq pandas -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.3/23.3 MB 29.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.7/143.7 kB 9.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 18.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 71.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 65.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.8/71.8 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.9/170.9 kB 13.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 kB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.7/203.7 kB 15.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 4.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opentelemetry-exporter-gcp-logging 1.11.0a0 requires opentelemetry-sdk<1.39.0,>=1.35.0, but you have opentelemetry-sdk 1.42.1 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-exporter-otlp-proto-common==1.38.0, but you have opentelemetry-exporter-otlp-proto-common 1.42.1 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-proto==1.38.0, but you have opentelemetry-proto 1.42.1 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-sdk~=1.38.0, but you have opentelemetry-sdk 1.42.1 which is incompatible.
google-adk 1.29.0 requires opentelemetry-api<1.39.0,>=1.36.0, but you have opentelemetry-api 1.42.1 which is incompatible.
google-adk 1.29.0 requires opentelemetry-sdk<1.39.0,>=1.36.0, but you have opentelemetry-sdk 1.42.1 which is incompatible.

In [ ]:
import pandas as pd
import chromadb
from sentence_transformers import SentenceTransformer
from groq import Groq
import os

In [ ]:
GROQ_API_KEY="your_api_key"
os.environ["GROQ_API_KEY"]=GROQ_API_KEY
groq_client = Groq(api_key=GROQ_API_KEY)

In [ ]:
ds=pd.read_csv("/content/college_notes.csv")
ds.shape

(15, 4)

In [ ]:
ds.columns.tolist()

['note_id', 'subject', 'topic', 'content']

In [ ]:
ds.head()

,note_id,subject,topic,content
0,N001,Data Engineering,ETL Pipelines,ETL stands for Extract Transform Load. It is t...
1,N002,Data Engineering,SQL Databases,A database is an organized collection of data ...
2,N003,Data Engineering,Data Cleaning,Data cleaning involves fixing or removing inco...
3,N004,Data Engineering,APIs and Data Collection,An API or Application Programming Interface al...
4,N005,Data Engineering,Big Data and PySpark,Big Data refers to extremely large datasets th...

In [ ]:
ds['subject'].value_counts()

subject
Data Engineering      5
Machine Learning      5
Generative AI         3
Python Programming    2
Name: count, dtype: int64

In [ ]:
ds[['note_id','topic','content']].to_string(index=False)

'note_id                          topic                                                                                                                                                                                                                                                                             content\n   N001                  ETL Pipelines                                                            ETL stands for Extract Transform Load. It is the process of collecting raw data from different sources transforming it into a clean and structured format and loading it into a database or data warehouse for analysis.\n   N002                  SQL Databases                                                                   A database is an organized collection of data stored electronically. SQL or Structured Query Language is used to interact with relational databases. Common SQL commands include SELECT INSERT UPDATE and DELETE.\n   N003                  Data Cleaning                                                                  Data cleaning involves fixing or removing incorrect incomplete duplicate or corrupted data. Common cleaning tasks include handling missing values removing duplicates fixing data types and standardizing formats.\n   N004       APIs and Data Collection                                                    An API or Application Programming Interface allows two software applications to talk to each other. In data engineering APIs are used to fetch data from external services like weather data stock prices or social media feeds.\n   N005           Big Data and PySpark                                  Big Data refers to extremely large datasets that cannot be processed by traditional tools. Apache Spark is a distributed computing framework that processes big data across multiple machines simultaneously. PySpark is the Python API for Spark.\n   N006            Supervised Learning                     Supervised learning is a type of machine learning where the model learns from labeled data. The model is given input features and correct output labels and it learns to predict outputs for new unseen inputs. Examples include classification and regression.\n   N007               Model Evaluation                                    Model evaluation measures how well a machine learning model performs. Common metrics include accuracy for classification and Mean Absolute Error and R-squared for regression. A good model generalizes well to new data it has not seen before.\n   N008            Feature Engineering                                        Feature engineering is the process of selecting transforming and creating input variables that help machine learning models learn better. This includes encoding categorical variables scaling numerical features and handling missing data.\n   N009                 Decision Trees                                                 A decision tree is a machine learning model that makes predictions by asking a series of yes or no questions about the features. It splits data at each node based on the feature that best separates the classes or reduces error.\n   N010                  Random Forest                                      Random Forest is an ensemble learning method that builds multiple decision trees and combines their predictions. It is more accurate and robust than a single decision tree and handles overfitting well by averaging results from many trees.\n   N011          Large Language Models                                                  A Large Language Model or LLM is an AI model trained on massive amounts of text data. It can generate human-like text answer questions summarize documents and perform many language tasks. Examples include GPT Claude and LLaMA.\n   N012             Prompt Engineering Prompt engineering is the practice of designing effective instructions or inputs for AI language models. A good prompt gives the model clear context specific instructions and examples if needed. Techniques include zero-shot few-shot role-based and chain-of-thought prompting.\n   N013 Retrieval Augmented Generation  RAG or Retrieval Augmented Generation is a technique where an AI model first retrieves relevant documents from a knowledge base and then generates an answer based on those retrieved documents. This reduces hallucination and allows AI to answer questions about specific data.\n   N014                 Pandas Library                        Pandas is a Python library used for data manipulation and analysis. It provides the DataFrame data structure which is like a table with rows and columns. Common operations include reading CSV files filtering rows grouping data and creating new columns.\n   N015             Data Visualization                           Data visualization is the process of representing data as charts graphs and visual formats. Python libraries like Matplotlib and Seaborn are used to create bar charts line plots histograms and pie charts that help humans understand patterns in data.'

In [ ]:
ds['content_length']=ds['content'].apply(len)

In [ ]:
ds[['topic','content_length']].to_string(index=False)

'                         topic  content_length\n                 ETL Pipelines             216\n                 SQL Databases             209\n                 Data Cleaning             210\n      APIs and Data Collection             224\n          Big Data and PySpark             242\n           Supervised Learning             255\n              Model Evaluation             240\n           Feature Engineering             236\n                Decision Trees             227\n                 Random Forest             238\n         Large Language Models             226\n            Prompt Engineering             275\nRetrieval Augmented Generation             274\n                Pandas Library             252\n            Data Visualization             249'

In [ ]:
document=ds['content'].tolist()

In [ ]:


ids=[f"note_{row['note_id']}" for row in ds.to_dict('records')]
metadatas=[
    {"subject": row['subject'],"topic": row['topic']}
    for row in ds.to_dict('records')
]
print(f"Total chunks prepared: {len(document)}")
print(f"first document ID: {ids[0]}")
print(f"first document metadata: {metadatas[0]}")
print(f"first 100 chars of doc: {document[0][:100]}")

Total chunks prepared: 15
first document ID: note_N001
first document metadata: {'subject': 'Data Engineering', 'topic': 'ETL Pipelines'}
first 100 chars of doc: ETL stands for Extract Transform Load. It is the process of collecting raw data from different sourc

In [ ]:
print("loading embedding model")
embedding_model=SentenceTransformer('all-MiniLM-L6-v2')
print("embedding model loaded")
test_embedding = embedding_model.encode("This is test sentence")
print(test_embedding.shape)
print(test_embedding[:5])

loading embedding model

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

embedding model loaded
(384,)
[ 0.07495026  0.07674191 -0.01143933  0.09722367  0.01962913]

In [ ]:
chroma_client=chromadb.Client()
collection=chroma_client.get_or_create_collection(name='college_notes_rag')
print("chroma db created successfully")
print(f"documents in collection: {collection.count()}")

chroma db created successfully
documents in collection: 0

In [ ]:
print("generating embedding for 15 documents")
embeddings=embedding_model.encode(document, show_progress_bar=True)
print(embeddings.shape)
embedding_list=embeddings.tolist()
collection.add(
    documents=document,
    metadatas=metadatas,
    ids=ids,
    embeddings=embedding_list
)
print(collection.count())

generating embedding for 15 documents

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

(15, 384)
15

In [ ]:
def retrieve_relevant_chuncks(question, top_k=3):
  question_embedding=embedding_model.encode(question).tolist()
  results=collection.query(
      query_embeddings=[question_embedding],
      n_results=top_k
  )
  return results

In [ ]:
test_question =" what is machine learning and how does it work in data engineering"
print(test_embedding)

results=retrieve_relevant_chuncks(test_question, top_k=3)
print("top 3 retrieved chunks")

for i, (doc,dist,meta) in enumerate(zip(
    results['documents'][0],
    results['distances'][0],
    results['metadatas'][0]
)):
  print(f"Results {i+1}")
  print(f"Subject: {meta['subject']}")
  print(f"topic: {meta['topic']}")
  print(f"distance: {dist}")
  print(f"content: {doc[:100]}")

[ 7.49502555e-02  7.67419115e-02 -1.14393318e-02  9.72236693e-02
  1.96291320e-02  7.49990577e-03  5.25962673e-02 -1.51912554e-03
  1.05633195e-02  4.59739938e-02  1.04660951e-01 -7.69618452e-02
  2.33884621e-03  2.84159947e-02  2.34545744e-03 -2.78552342e-02
  4.36108746e-02 -5.35113923e-02 -7.77004734e-02  2.51303706e-02
  4.50356416e-02  2.45232433e-02 -2.27372963e-02  2.01834049e-02
  1.77401565e-02  2.19538882e-02 -4.97626364e-02  6.96432637e-03
  9.39383656e-02 -2.56639924e-02 -5.24299890e-02  1.44201396e-02
  3.37429233e-02  6.18972182e-02  1.42109599e-02 -9.18646716e-03
  1.78935789e-02  1.48466332e-02  8.23294278e-03  1.00327842e-02
 -2.78042653e-03 -1.22415647e-01  2.43236218e-02  1.40198795e-02
  3.05844527e-02  9.90021508e-03 -3.11313439e-02  2.37757936e-02
 -6.04552729e-03 -3.89494672e-02 -5.96202835e-02 -5.96039481e-02
 -7.59048015e-02 -3.66356149e-02  6.86025666e-03  2.27700733e-02
  2.02777795e-02  1.02620460e-02  2.50371359e-02  4.11647335e-02
  2.97970022e-03 -2.21210327e-02 -8.91575962e-02  4.93386984e-02
  1.37678832e-01 -1.48653975e-02 -3.35379764e-02 -1.02411740e-01
 -4.38964665e-02  7.61278206e-03  1.53156566e-02  4.34159487e-02
  3.28928828e-02  2.45599318e-02  1.95371117e-02  3.08354548e-03
 -8.66569486e-03 -9.51035172e-02  1.17755644e-01  5.20047136e-02
 -6.89961612e-02 -1.27298117e-01 -1.79362632e-02  4.74771261e-02
  1.40445745e-02  2.65486073e-02  8.44526961e-02 -5.36845475e-02
 -1.13209225e-01  9.72272363e-03  5.68506401e-03 -2.95203049e-02
  2.50300718e-03  2.31039803e-02 -3.54568884e-02 -1.28612658e-02
 -5.67472838e-02 -1.98532529e-02  1.76855214e-02  9.78612453e-02
  1.70025118e-02  4.24700268e-02  2.16615833e-02  2.18427740e-02
 -1.12325840e-01 -8.92571434e-02  2.46600024e-02 -6.35865703e-02
  4.69544306e-02 -7.41226086e-03 -2.79407315e-02 -1.46055443e-03
  4.82813753e-02  2.84724925e-02 -3.94805185e-02 -2.16036495e-02
 -1.34951800e-01  5.19062765e-02 -5.33614643e-02  3.08791511e-02
  7.29077458e-02  6.78947419e-02 -4.48273197e-02 -1.90051331e-04
 -5.59359193e-02 -6.85795397e-02  9.11250412e-02 -5.34514950e-33
 -6.82051433e-03 -7.03998134e-02  3.39896120e-02  5.93490750e-02
 -2.88725190e-04  5.78801008e-03 -1.19256787e-02  8.03554505e-02
 -3.83321233e-02 -3.16768587e-02 -5.00304438e-03 -1.05600327e-01
  1.44945914e-02  3.68467942e-02  7.77304322e-02  9.52551812e-02
 -6.38178885e-02  5.71446419e-02 -4.11370285e-02  6.05685450e-02
  1.04158130e-02 -1.81057323e-02 -2.07070578e-02 -9.59801748e-02
 -9.15578157e-02 -7.99852014e-02  9.48746223e-03 -6.77989237e-03
 -4.59149815e-02  1.97482780e-02 -1.19210351e-02  1.73558872e-02
 -7.99108893e-02  7.23410472e-02  1.35191465e-02  4.80900258e-02
  5.32546230e-02 -6.70184344e-02 -4.04967135e-03  2.05769967e-02
 -5.58457896e-02 -3.14850099e-02  5.86527959e-03  1.02452375e-02
  6.67491257e-02 -1.72983433e-04 -2.77585108e-02 -2.57400703e-02
  3.48878466e-03  2.81044226e-02 -2.52606589e-02  4.29575145e-02
  2.26761159e-02 -3.14672552e-02  4.70095687e-02  7.43872449e-02
  4.85012121e-02  5.91654424e-03 -1.89845376e-02  6.46980405e-02
  3.70383332e-03  3.86199914e-02 -5.41861020e-02  6.45333752e-02
  1.56944077e-02  1.28030907e-02 -3.99919488e-02 -7.41039217e-02
  9.72486213e-02  3.82341295e-02 -4.03340943e-02 -5.42784892e-02
 -3.84207182e-02  7.51618296e-02 -1.11461803e-02 -5.20163700e-02
  2.91646495e-02  7.26305619e-02  1.00806374e-02 -1.47221955e-02
  4.46384996e-02 -1.16778836e-01  1.36579927e-02 -3.11832242e-02
 -8.32307786e-02  1.16360718e-02 -4.90014162e-03 -1.10643961e-01
  7.25865550e-03 -2.34972425e-02 -1.12256529e-02 -2.98566208e-03
  3.31870131e-02 -7.35690026e-03  7.30905235e-02  2.42335636e-33
 -7.40317702e-02  7.35900700e-02 -8.55584368e-02  6.62557632e-02
  8.80754367e-02 -3.45463976e-02  9.27132517e-02 -4.39223535e-02
 -4.88758348e-02  1.24725640e-01 -4.67959419e-03  8.43500160e-03
 -1.19131673e-02 -3.20465374e-03  3.51746790e-02  1.63627695e-02
  2.79225148e-02 -3.07962168e-02 -3.10864039e-02  1.02448538e-02
 -4.53598090e-02  1.33398503e-01  2.75145750e-02  5.41138239e-02
 -6.44511059e-02 -5.04403794e-03 -4.36321693e-03 -6.23399131e-02
 -7.62609690e-02  2.25471612e-02  3.33547965e-02 -4.02358696e-02
 -5.50324507e-02  1.57129131e-02  4.01980206e-02 -2.52767708e-02
  9.91550162e-02 -6.36669919e-02 -4.47524041e-02  9.94103625e-02
  3.64413373e-02  1.91550162e-02  3.40163000e-02  8.68191570e-02
  1.71785392e-02  2.03770008e-02 -7.29299244e-03 -1.03796989e-01
 -1.05535015e-02  6.97338581e-02 -6.69881031e-02  1.85825918e-02
 -2.81457901e-02  1.54689485e-02 -5.18403091e-02  3.68128978e-02
 -6.27565458e-02 -3.85063812e-02 -3.05611100e-02  1.22351246e-02
 -7.42292106e-02  6.87810481e-02  9.56893805e-03  3.97219323e-02
  5.31714223e-02 -6.78377599e-02 -7.23175481e-02  7.21653476e-02
  3.62380296e-02 -2.93948501e-02  7.02488795e-02  3.79334390e-02
 -9.70780477e-02 -4.11770754e-02 -3.82518582e-02 -8.33809599e-02
 -7.27249235e-02 -2.49133855e-02 -2.37035193e-02 -8.08145925e-02
 -7.41314841e-03 -6.07417785e-02 -1.79687589e-02  1.36410147e-02
 -5.69829382e-02  2.53796019e-02  4.75890227e-02 -1.80649012e-02
  3.42685054e-03  3.28114815e-02  1.08201103e-02 -2.44474337e-02
  4.57404256e-02 -1.31125106e-02 -1.69648137e-02 -1.71687020e-08
 -2.19294988e-02 -5.03955521e-02 -1.10434089e-02  1.40583236e-02
 -1.50067341e-02  2.71148384e-02  5.29036261e-02 -4.48430628e-02
 -3.59569378e-02 -9.03859828e-03  6.35140240e-02  5.35802878e-02
 -5.30032776e-02  1.77898388e-02  3.64470594e-02 -2.89151147e-02
 -1.31941857e-02  1.60491117e-03 -2.28540017e-03  4.99904156e-02
 -3.55304480e-02  2.23602913e-02  2.19002403e-02  7.44066015e-02
 -1.41262566e-03  3.98332179e-02  9.36296955e-02  8.41341093e-02
  1.09541118e-02  4.34891209e-02  1.01541705e-01  8.58925432e-02
 -3.37059125e-02 -2.88560223e-02 -4.21720417e-03  7.12292120e-02
  4.87684309e-02 -3.81199233e-02  5.26256934e-02  5.83902095e-03
 -8.15549642e-02  1.93382353e-02 -1.45029882e-02  6.45951554e-02
 -2.48749927e-02 -7.19884932e-02 -4.95334566e-02 -2.17106491e-02
 -3.05779092e-02 -9.38495547e-02 -3.28198336e-02 -8.64452217e-03
  1.55731635e-02 -1.39126461e-02  3.80513445e-02  3.85844195e-03
  1.28695052e-02 -2.63588261e-02 -1.04269065e-01  2.05659159e-02
  8.89914259e-02  2.33913250e-02  1.00052409e-01 -1.03704721e-01]
top 3 retrieved chunks
Results 1
Subject: Machine Learning
topic: Supervised Learning
distance: 0.7183249592781067
content: Supervised learning is a type of machine learning where the model learns from labeled data. The mode
Results 2
Subject: Machine Learning
topic: Feature Engineering
distance: 1.0548670291900635
content: Feature engineering is the process of selecting transforming and creating input variables that help
Results 3
Subject: Machine Learning
topic: Decision Trees
distance: 1.09181547164917
content: A decision tree is a machine learning model that makes predictions by asking a series of yes or no q

In [ ]:
def build_context_from_results(results):
  context_parts=[]
  for i, (doc, meta) in enumerate(zip(
      results['documents'][0],
      results['metadatas'][0]
  )):
    chunk_text=f"[Source {i+1}: {meta['subject']} - {meta['topic']}]\n{doc}"
    print("top 3 retrieval chuncks")

In [ ]:
def generate_rag_answer(question, context):
  system_prompt="""You are a helpful academic assistant for engineering students.
  You will be given context retrieved from a college knowledge base, and a students's question

  RULES:
  1. Answer only using the information provided in the context below.
  2. If the answer is not found in context, say exactly.
   "I dont have enough information to answer your question"
  3.do not use your general training knowledge
  4.keep answer clear, accurate, and beginner friendly
  """

  user_prompt="""
      explain big bang theory and is impact on expanding universe
  """

  response = groq_client.chat.completions.create(
      model="llama-3.1-8b-instant",
      messages=[
          {"role": "system", "content": system_prompt},
          {"role": "user", "content": user_prompt}
      ],
      temperature=0.1,
      max_tokens=500
  )

  answer= response.choices[0].message.content

  return answer


print("Rag function defined")

Rag function defined

In [ ]:
def ask_college_assistant(question, top_k=3, verbose=True):
  if verbose:
    print(f"Question: {question}")

  # 1. Retrieve relevant documents
  results = retrieve_relevant_chuncks(question, top_k=top_k)
  if verbose:
    print(f"Retrieved {len(results['documents'][0])} relevant document(s).")

  # 2. Build context from retrieved documents
  context = build_context_from_results(results)
  if verbose:
    print("Context built from relevant documents.")
    print("\n--- Retrieved Context ---")
    print(context)
    print("-------------------------")

  # 3. Generate answer using RAG
  answer = generate_rag_answer(question, context)

  if verbose:
    print("\n--- Generated Answer ---")
    print(answer)
    print("-------------------------")

  return answer